"""Second migration

Revision ID: 614133a7a2f1
Revises: 62168adf7ea4
Create Date: 2021-03-23 21:09:59.228139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614133a7a2f1'
down_revision = '62168adf7ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
