"""Second migration

Revision ID: eb318aa864d2
Revises: 4b53bf283960
Create Date: 2021-03-23 20:58:44.420702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb318aa864d2'
down_revision = '4b53bf283960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
